## Neovim-powered Vim emulation for Godot's script editor.
##
## GodotNeovim provides Vim keybindings in Godot's script editor
## using an embedded Neovim instance as the backend.
##
## @tutorial(GitHub): https://github.com/shiena/godot-neovim
##
## [br][br][b]Modes[/b][br]
## [code]Normal[/code] - Default mode for navigation and commands[br]
## [code]Insert[/code] - Text input mode (i, a, o, etc.)[br]
## [code]Visual[/code] - Character selection (v)[br]
## [code]Visual Line[/code] - Line selection (V)[br]
## [code]Visual Block[/code] - Block selection (gv)[br]
## [code]Replace[/code] - Overwrite mode (R)[br]
## [code]Command[/code] - Ex command mode (:)[br]
##
## [br][b]Basic Motions[/b][br]
## [code]h j k l[/code] - Left, Down, Up, Right[br]
## [code]w b e ge[/code] - Word forward, backward, end, back end[br]
## [code]W B E[/code] - WORD (whitespace-delimited)[br]
## [code]0 $ ^[/code] - Line start, Line end, First non-blank[br]
## [code]gg G[/code] - File start, File end[br]
## [code]{count}G[/code] - Go to line number[br]
## [code]%[/code] - Matching bracket[br]
## [code]{ }[/code] - Previous/Next paragraph[br]
## [code]H M L[/code] - Screen top, middle, bottom[br]
## [code]gj gk[/code] - Display line down/up (wrapped lines)[br]
## [code]g0 g$ g^ g_[/code] - Display line start/end/first non-blank/last non-blank[br]
##
## [br][b]Scrolling[/b][br]
## [code]Ctrl+F Ctrl+B[/code] - Full page down/up[br]
## [code]Ctrl+D Ctrl+U[/code] - Half page down/up[br]
## [code]Ctrl+Y Ctrl+E[/code] - Scroll viewport up/down[br]
## [code]zz zt zb[/code] - Center, top, bottom cursor line[br]
##
## [br][b]Find Motions[/b][br]
## [code]f{char}[/code] - Find char forward[br]
## [code]F{char}[/code] - Find char backward[br]
## [code]t{char}[/code] - Till char forward[br]
## [code]T{char}[/code] - Till char backward[br]
## [code]; ,[/code] - Repeat last find / reverse[br]
##
## [br][b]Block/Method Jumps[/b][br]
## [code][{ ]}[/code] - Previous/Next unmatched {[br]
## [code][( ])[/code] - Previous/Next unmatched ([br]
## [code][m ]m[/code] - Previous/Next method start (requires treesitter, not available for GDScript)[br]
##
## [br][b]Operators[/b][br]
## [code]d{motion}[/code] - Delete[br]
## [code]c{motion}[/code] - Change (delete and enter insert)[br]
## [code]y{motion}[/code] - Yank (copy)[br]
## [code]>{motion}[/code] - Indent right[br]
## [code]<{motion}[/code] - Indent left[br]
## [code]gq{motion}[/code] - Format[br]
## [code]gu{motion}[/code] - Lowercase[br]
## [code]gU{motion}[/code] - Uppercase[br]
## [code]g~{motion}[/code] - Toggle case[br]
##
## [br][b]Operator Shortcuts[/b][br]
## [code]dd cc yy[/code] - Operate on entire line[br]
## [code]D C Y[/code] - Operate to end of line[br]
## [code]x X[/code] - Delete char under/before cursor[br]
## [code]s S[/code] - Substitute char/line[br]
## [code]r{char}[/code] - Replace char under cursor[br]
## [code]~[/code] - Toggle case of char[br]
## [code]J gJ[/code] - Join lines (with/without space)[br]
## [code]>> <<[/code] - Indent/Unindent line[br]
##
## [br][b]Paste[/b][br]
## [code]p P[/code] - Paste after/before[br]
## [code]gp gP[/code] - Paste and move cursor after[br]
## [code][p ]p[/code] - Paste with indent adjustment[br]
##
## [br][b]Text Objects[/b][br]
## [code]iw aw[/code] - Inner/Around word[br]
## [code]iW aW[/code] - Inner/Around WORD[br]
## [code]i" a" i' a'[/code] - Inner/Around quotes[br]
## [code]i( a( i) a)[/code] - Inner/Around parentheses[br]
## [code]i{ a{ i} a}[/code] - Inner/Around braces[br]
## [code]i[ a[ i] a][/code] - Inner/Around brackets[br]
## [code]i< a< i> a>[/code] - Inner/Around angle brackets[br]
## [code]ie ae[/code] - Inner/Around entire buffer[br]
##
## [br][b]Insert Mode Entry[/b][br]
## [code]i a[/code] - Insert before/after cursor[br]
## [code]I A[/code] - Insert at first non-blank/end of line[br]
## [code]o O[/code] - Open line below/above[br]
## [code]gI[/code] - Insert at column 0[br]
## [code]gi[/code] - Insert at last insert position[br]
## [code]R[/code] - Replace mode (overwrite)[br]
## [code]Escape Ctrl+[[/code] - Return to normal mode[br]
##
## [br][b]Visual Mode[/b][br]
## [code]v[/code] - Character-wise visual[br]
## [code]V[/code] - Line-wise visual[br]
## [code]Ctrl+V gv[/code] - Visual block (gv as alternative)[br]
## [code]Ctrl+B[/code] - Switch to visual block (in visual mode)[br]
## [code]o[/code] - Toggle selection direction[br]
##
## [br][b]Marks[/b][br]
## [code]m{a-z}[/code] - Set mark[br]
## [code]'{a-z}[/code] - Jump to mark (line)[br]
## [code]`{a-z}[/code] - Jump to mark (exact position)[br]
## [code]:marks[/code] - Show all marks[br]
##
## [br][b]Registers[/b][br]
## [code]"{a-z}{op}[/code] - Use named register[br]
## [code]"+ "*[/code] - System clipboard[br]
## [code]"_[/code] - Black hole register[br]
## [code]"0[/code] - Yank register[br]
## [code]:registers :reg[/code] - Show all registers[br]
##
## [br][b]Macros[/b][br]
## [code]q{a-z}[/code] - Start recording macro[br]
## [code]q[/code] - Stop recording[br]
## [code]@{a-z}[/code] - Play macro[br]
## [code]@@[/code] - Repeat last macro[br]
##
## [br][b]Search[/b][br]
## [code]/{pattern}[/code] - Search forward[br]
## [code]?{pattern}[/code] - Search backward[br]
## [code]n N[/code] - Next/Previous match[br]
## [code]* #[/code] - Search word under cursor forward/backward[br]
##
## [br][b]Go Commands[/b][br]
## [code]gd[/code] - Go to definition (LSP)[br]
## [code]gf[/code] - Go to file under cursor[br]
## [code]gx[/code] - Open URL under cursor[br]
## [code]gt gT[/code] - Next/Previous tab[br]
##
## [br][b]Info Commands[/b][br]
## [code]K[/code] - Show documentation (LSP)[br]
## [code]ga[/code] - Show ASCII/Unicode value[br]
## [code]Ctrl+G[/code] - Show file info[br]
##
## [br][b]Folding[/b][br]
## [code]za[/code] - Toggle fold[br]
## [code]zo zc[/code] - Open/Close fold[br]
## [code]zR zM[/code] - Open/Close all folds[br]
##
## [br][b]Jump List[/b][br]
## [code]Ctrl+O[/code] - Jump back[br]
## [code]Ctrl+I[/code] - Jump forward[br]
## [code]:jumps :ju[/code] - Show jump list[br]
##
## [br][b]Number Operations[/b][br]
## [code]Ctrl+A[/code] - Increment number[br]
## [code]Ctrl+X[/code] - Decrement number[br]
##
## [br][b]Undo/Redo[/b][br]
## [code]u[/code] - Undo[br]
## [code]Ctrl+R[/code] - Redo[br]
## [code].[/code] - Repeat last change[br]
##
## [br][b]Ex Commands[/b][br]
## [code]:help :h[/code] - Open this help[br]
## [code]:version :ver[/code] - Show version in status label[br]
## [code]:w :wa :wall[/code] - Save / Save all[br]
## [code]:q :qa :qall[/code] - Close / Close all[br]
## [code]:wq :x[/code] - Save and close[br]
## [code]:wqa[/code] - Save all and close all[br]
## [code]:e {file}[/code] - Open file[br]
## [code]:e! :edit![/code] - Reload from disk[br]
## [code]:bn :bp :bd[/code] - Next/Previous/Delete buffer[br]
## [code]:ls[/code] - List buffers[br]
## [code]:{number}[/code] - Go to line[br]
## [code]:%s/old/new/g[/code] - Substitute all[br]
## [code]:g/{pattern}/d[/code] - Delete matching lines[br]
## [code]:sort[/code] - Sort lines[br]
## [code]:t {line}[/code] - Copy line to after {line}[br]
## [code]:m {line}[/code] - Move line to after {line}[br]
## [code]:changes[/code] - Show change list[br]
## [code]ZZ[/code] - Save and close (normal mode)[br]
## [code]ZQ[/code] - Close without saving[br]
## [code]@:[/code] - Repeat last Ex command[br]
## [code]g&[/code] - Repeat last :s on entire file[br]
## [code]Up Down[/code] - Browse command history[br]
##
## [br][b]Settings[/b][br]
## Configure via [code]Editor > Editor Settings > Godot Neovim[/code].[br]
## [i]Note: Enable "Advanced Settings" toggle in Editor Settings to see the godot_neovim section.[/i][br]
## [code]neovim_executable_path[/code] - Path to Neovim executable[br]
## [code]neovim_clean[/code] - Equivalent to --clean startup option (default: true)[br]
## [code]timeoutlen[/code] - Time (ms) to wait for a mapped sequence to complete (advanced)[br]
##
## [br][b]Limitations[/b][br]
## - Insert mode commands (Ctrl+O, Ctrl+W, etc.) not available[br]
## - Neovim config (init.lua, plugins) not loaded by default (neovim_clean=true)[br]
## - Uses Godot's undo system instead of Neovim's[br]
## - [code][m ]m[/code] method jumps require treesitter (GDScript not supported by Neovim)[br]
## - [code]:e![/code] leaves (*) marker until tab switch (gt/gT)
class_name GodotNeovim
extends RefCounted
